logging:
  level:
    root: INFO
    com.java_template.application.processor.accrual: DEBUG
    com.java_template.application.processor.eod_batch: DEBUG
    com.java_template.application.criterion.accrual: DEBUG
    com.java_template.application.criterion.eod_batch: DEBUG


server:
  port: 8080
  forward-headers-strategy: framework

spring:
  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    try-it-out-enabled: true
    csrf:
      enabled: false

